<a href="https://colab.research.google.com/github/iAmanSharan/NLP-with-hugging-face/blob/main/funWtihTransformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pip install datasets evaluate transformers[sentencepiece]

In [ ]:

pip install datasets evaluate transformers[sentencepiece]

In [ ]:
from transformers import pipeline
analysis = pipeline("sentiment-analysis")
a = "Hi , how are you ?"
analysis(a)

In [ ]:
classify = pipeline("zero-shot-classification")
classify(
    "I have been learning about how to sex leads to better cognitive function from neuroscientific point of view and from pshycology",
    candidate_labels=["Education" , "sex" , "marriage" , "relationship" , "research" , "leanring " , "neuroscience" , "Andrew Huberman"],
)

In [ ]:
from transformers import AutoTokenizer
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
sentences = [
    "Hi, my name is Aman Raj , I feel great" ,
    "your so dumb"
]
input = tokenizer(sentences,padding = True , truncation = True , return_tensors = "tf")
print(input)

In [ ]:
from transformers import TFAutoModel
model = TFAutoModel.from_pretrained(checkpoint)

In [ ]:
from transformers import TFAutoModelForSequenceClassification
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
output = model(input)

In [ ]:
print(output)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-3.1404579,  3.3785257],
       [ 4.6875496, -3.6951082]], dtype=float32)>, hidden_states=None, attentions=None)


In [ ]:
import tensorflow as tf
prediction = tf.math.softmax(output.logits , axis =  1)
print(prediction)

tf.Tensor(
[[1.4729943e-03 9.9852693e-01]
 [9.9977130e-01 2.2874864e-04]], shape=(2, 2), dtype=float32)


In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
sequence = "My name is Aman Raj"
token = tokenizer.tokenize(sequence)
print(token)

In [ ]:
id = tokenizer.convert_tokens_to_ids(token)
print(id)

In [ ]:
from datasets import load_dataset
raw_data = load_dataset("glue" , "mrpc")
print(raw_data)

Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})


In [ ]:
raw_data["train"][0]

{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 'label': 1,
 'idx': 0}